### ISSUE TITLE
[Question] the results using the Berea.raw are not the same

### ISSUE THREAD

**Issue by ZHHYKU** [aliraeini/pnextract#3]
I used the image Berea.raw with sizes: 400 400 400 and resolution 5.345. The format of Image.mhd is:
ObjectType =  Image
NDims =       3
ElementType = MET_UCHAR

DimSize =        400  400  400
ElementSpacing = 5.345   5.345   5.345
Offset =         0   0   0
ElementDataFile = Berea.raw

But the results are not the same as those results in the website (https://figshare.com/articles/Berea_Sandstone/1153794). Did I miss something in the IMAGE.mhd? 
Thank you!

**Comment by aliraeini** [comment]
This is expected, this code is different from the original code used to produce the network models from (2007-2009) on our website, and produces networks with different number of pores and throats,shape-factors etc. 
For your reference, what you should check is that the underlying physical properties (absolute permeability, resistivity/formation-factor) are predicted with a good accuracy compared to direct-simulations and experimental counter-parts.  Network/discretization parameters (like number of pores and throats) are of little physical meaning.  Properties like average pore and throat sizes when computed using volume-weighted approach can be linked to physical properties.  So you need to check these properties are not significantly different from the results presented back in 2007-2009.

**Comment by ZHHYKU** [comment]
Thanks for your replying！
