### ISSUE TITLE
extract problems

### ISSUE THREAD

**Issue by asukanana** [aliraeini/pnextract#4]
When I tried to repeat the berea model, I ran into some problems. When I opened the berea.nhrd file (400/400 files) in IMAGEJ and saved the output as an mhd file, I used pnextract.EXE to process the mhd file, and then the output the tif file showed 402/402 files. The mhd file output at the same time shows Offset = -5.345e-006 -5.345e-006 -5.345e-006 ElementByteOrderMSB = False 
How can I solve it?

**Comment by aliraeini** [comment]
The pnextract code adds one layer on each side of the image internally and when writting the IMAGE_VElems.mhd file; this extra layer represents the boundary sides. The extracted network should still report that the image size is 400^3 * 5.345e-006^3.

**Comment by asukanana** [comment]
That’s true. so when I get this (402/402)file, what should I do to make this file work as the berea.tif which show in https://github.com/PMEAL/OpenPNM/tree/dev/examples/notebooks/_fixtures/ICL-Sandstone(Berea). Thank you for your answer.

**Comment by aliraeini** [comment]
Berea.tif is the original image in tif format, I think, you can read/write that from ImageJ and pnextract supports it as input too.  The _link1.dat... files are the network in Oren/Statoil format on which you can  run a flow simulation.
