### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rpshi** [aliraeini/pnextract#6]
Hi, Ali

Thanks for sharing the great tool.

I am wondering if one has to have root access to install the tool (make -j for example)

Thanks,

R

**Comment by aliraeini** [comment]
No, the make uses only its own ($msRoot) folder.  so root access is not required.  For installing prerequisites, g++ compiler for insttance, having root access simplifies the job, but that is only if they are not available by default.  

Cheers, Ali

**Comment by rpshi** [comment]
Thanks, Ali. I compiled successfully in my own directory.
